# GENERATED HEADER START
name:                servant-websockets-client
version:             0.0.1
github:              "simspace/servant-websockets"
license:             BSD-3-Clause
author:              "Cary Robbins"
maintainer:          "SimSpace Engineering"
copyright:           "2019 SimSpace"
category:            Web
synopsis:            Client library for using websockets with servant
description:         Please see the README on GitHub at <https://github.com/simspace/servant-websockets#readme>
# GENERATED HEADER END

default-extensions:
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- RankNTypes
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies
- UndecidableInstances

dependencies:
- base
- binary
- bytestring
- mtl
- network
- servant-client
- servant-client-core
- servant-websockets-core
- websockets

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -O2

when:
  - condition: impl(ghc < 9.4)
    ghc-options:
    - -eventlog
