# GENERATED HEADER START
name:                servant-websockets-server
version:             0.0.0.1
github:              "simspace/servant-websockets"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 SimSpace"
category:            Web
synopsis:            Server library for using websockets with servant
description:         Please see the README on GitHub at <https://github.com/simspace/servant-websockets#readme>
# GENERATED HEADER END

default-extensions:
- DataKinds
- AllowAmbiguousTypes
- FlexibleInstances
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeFamilies

dependencies:
- base
- bytestring
- exceptions
- mtl
- resourcet
- servant-server
- servant-websockets-core
- wai-websockets
- websockets

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -O2
  when:
    - condition: impl(ghc < 9.4)
      ghc-options:
      - -eventlog
