# GENERATED HEADER START
name:                servant-websockets-examples
version:             0.0.1
github:              "simspace/servant-websockets"
license:             BSD-3-Clause
author:              "Cary Robbins"
maintainer:          "SimSpace Engineering"
copyright:           "2019 SimSpace"
category:            Web
synopsis:            Example server, client, and docs for servant-websockets
description:         Please see the README on GitHub at <https://github.com/simspace/servant-websockets#readme>
# GENERATED HEADER END

default-extensions:
- DataKinds
- DeriveAnyClass
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- FlexibleInstances
- LambdaCase
- NamedFieldPuns
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeOperators

dependencies:
- base
- aeson
- http-client
- servant
- servant-client
- servant-client-core
- servant-docs
- servant-server
- servant-websockets-client
- servant-websockets-core
- servant-websockets-docs
- servant-websockets-server
- text
- warp
- websockets

library:
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -O0
  when:
    - condition: impl(ghc < 9.4)
      ghc-options:
      - -eventlog
  source-dirs:
  - src

executables:
  servant-websocket-example:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - servant-websockets-examples
