#!/bin/bash

set -e

cd "$(dirname $0)/.."

subprojects=(core client server test)

packageYamlHeader() {
  local subproject=$1
  cat <<HERE > "$tmp"
# GENERATED HEADER START
name:                servant-websockets-$subproject
version:             0.0.0.1
github:              "simspace/servant-websockets"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 SimSpace"
# GENERATED HEADER END
HERE
}

for subproject in "${subprojects[@]}"; do
  tmp=$(mktemp)
  packageYamlHeader "$subproject" > "$tmp"
  grep -F -A9999 '# GENERATED HEADER END' "$subproject/package.yaml" \
    | tail -n+2 >> "$tmp"
  mv "$tmp" "$subproject/package.yaml"
done
