#!/bin/bash

set -e

cd "$(dirname $0)/.."

subprojects=(core client docs examples server test)

packageYamlHeader() {
  local subproject=$1
  cat <<HERE > "$tmp"
# GENERATED HEADER START
name:                servant-websockets-$subproject
version:             0.0.1
github:              "simspace/servant-websockets"
license:             BSD-3-Clause
author:              "Cary Robbins"
maintainer:          "SimSpace Engineering"
copyright:           "2019 SimSpace"
category:            Web
synopsis:            $(synopsis "$subproject")
description:         Please see the README on GitHub at <https://github.com/simspace/servant-websockets#readme>
# GENERATED HEADER END
HERE
}

synopsis() {
  local subproject=$1
  case "$subproject" in
    examples) echo "Example server, client, and docs for servant-websockets";;
    test) echo "Test suite for servant-websockets";;
    *)
      local title
      title=$(tr '[:lower:]' '[:upper:]' <<< "${subproject:0:1}")${subproject:1}
      echo "$title library for using websockets with servant"
      ;;
  esac
}

for subproject in "${subprojects[@]}"; do
  tmp=$(mktemp)
  packageYamlHeader "$subproject" > "$tmp"
  grep -F -A9999 '# GENERATED HEADER END' "$subproject/package.yaml" \
    | tail -n+2 >> "$tmp"
  mv "$tmp" "$subproject/package.yaml"
done
