# GENERATED HEADER START
name:                servant-websockets-docs
version:             0.0.0.1
github:              "simspace/servant-websockets"
license:             BSD3
author:              "Cary Robbins"
maintainer:          "carymrobbins@gmail.com"
copyright:           "2019 SimSpace"
category:            Web
synopsis:            Docs library for using websockets with servant
description:         Please see the README on GitHub at <https://github.com/simspace/servant-websockets#readme>
# GENERATED HEADER END

default-extensions:
- DataKinds
- FlexibleContexts
- FlexibleInstances
- KindSignatures
- OverloadedStrings
- PolyKinds
- ScopedTypeVariables
- TypeApplications
- TypeOperators

dependencies:
- base
- bytestring
- http-media
- lens
- servant
- servant-docs
- servant-websockets-core
- text

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Werror
  - -fwarn-tabs
  - -Wincomplete-uni-patterns
  - -O2
  when:
    - condition: impl(ghc < 9.4)
      ghc-options:
      - -eventlog
